### ISSUE TITLE
A bunch of hurdles

### ISSUE THREAD

**Issue by rmendelovits** [samuelpolat/telemetry.js#1]
Let me start by saying I'm really impressed with what you accomplished in the last 8 days and I wish you the best of success.

Here are some of the problems I found ... and how I overcame them

# 1. Getting Started README does not work for simple case

Your documentation has the following lines:

## Usage

    var telemetry = require('telemetry.js');

Track visits with:

    telemetry.trackVisit(req);

That's it!

However that did not work for me. I get the following error:

```
PS <PATH>/telemetry> npm start

> telemetrytest@1.0.0 <PATH>/telemetry
> node main.js

Server running at http://127.0.0.1:8081/
<PATH>\telemetry\main.js:5
   telemetry.trackVisit(request);
             ^

TypeError: telemetry.trackVisit is not a function
    at Server.<anonymous> (<PATH>\telemetry\main.js:5:14)
    at Server.emit (events.js:189:13)
    at parserOnIncoming (_http_server.js:676:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

To solve this, I changed

```telemetry.trackVisit(req);```

into

```telemetry({enableMongo: false}).trackVisit(req);```

# 2. No NULL check on geo, and NULL is returned when using private IP (like localhost)

```
<PATH>\telemetry\node_modules\telemetry.js\index.js:33
        var country = geo['country']
                         ^

TypeError: Cannot read property 'country' of null
    at Object.trackVisit (<PATH>\telemetry\node_modules\telemetry.js\index.js:33:26)
    at Server.<anonymous> (<PATH>\telemetry\main.js:5:36)
    at Server.emit (events.js:189:13)
    at parserOnIncoming (_http_server.js:676:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

Solution:

Change the Client Location code

```javascript
        // Client location
        var geo = geoip.lookup(ip)
        var country = geo['country']
        var region = geo['region']
        var city = geo['city']
```

to

```javascript
        // Client location
        var geo = geoip.lookup(ip)
        var country = geo ? geo['country'] : ''
        var region = geo ? geo['region'] : ''
        var city = geo ? geo['city'] : ''
```

# 3. If enableMongo is true, and connection is undefined, an undefined error is thrown.

Calling code:
```   telemetry({enableMongo: true}).trackVisit(request);```

```
<PATH>\telemetry.js\index.js:44
        if (dbEnabled === true && connection.length > 0) {
                                             ^

TypeError: Cannot read property 'length' of undefined
    at Object.trackVisit (<PATH>telemetry.js\index.js:44:46)
    at Server.<anonymous> (<PATH>\telemetry\main.js:5:35)
    at Server.emit (events.js:189:13)
    at parserOnIncoming (_http_server.js:676:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

Solution:

Change

`        // Track visit
        if (dbEnabled === true && connection.length > 0) {
          this.saveMongo(data)
        } else {
          this.saveJSON(data)
        };`

to

`        // Track visit
        if (dbEnabled === true) {
            if(connection.length > 0) {
                this.saveMongo(data)
            } else {
                throw new Error('You cannot set enableMongo to true unless you pass a db connection string');
        } else {
          this.saveJSON(data)
        };`

# 4. Structural Problems

This is not your fault, just something to be aware of. 

a) Someone who sets their own user-agent, x-forwarded-for, and referer can spoof 7/9 of the fields.
b) referer is particularly dangerous because the value passed goes directly in the object.
c) saveMongo and saveJSON are exported. This means anyone can write anything to your log, provided they match the mongoose types

Here are a couple of suggestions to improve this product

1. Support sequelize for sql/postgresql/sqlite, and also support redis
2. have a simple REST API surrounding telemetry. [Medium Tutorial](https://medium.freecodecamp.org/how-to-build-blazing-fast-rest-apis-with-node-js-mongodb-fastify-and-swagger-114e062db0c9)
3. Use [redact-pii](https://www.npmjs.com/package/redact-pii) to remove accidentally grabbed IP addresses and other sensitive information from the path.

Thanks so much for your contribution, I can't wait to see where this project ends up in a month!

**Comment by samuelpolat** [comment]
Thank you very much @rmendelovits for your feedback! 
Telemetry is my first open-source project, so I really appreciate every contribution.

I have fixed most of the described issues in [telemetry.js@1.1.3](https://www.npmjs.com/package/telemetry.js/v/1.1.3), including:

- [x] Fixed README
- [x] NULL check for `geo`
- [x] Error for undefined connection

I will address the structural problems ASAP and implement your suggestions in the next update.

**Comment by rmendelovits** [comment]
Great Job!
